Repository gnieh/fs2-data, pull requests merged in 2023-10, with the labels that each got.

#426 Add Jq implementation
  build.sbt
  finite-state/shared/src/main/scala/fs2/data/mft/query/Query.scala
  finite-state/shared/src/main/scala/fs2/data/mft/query/QueryCompiler.scala
  finite-state/shared/src/main/scala/fs2/data/pfsa/Pred.scala
  finite-state/shared/src/main/scala/fs2/data/pfsa/Regular.scala
  finite-state/shared/src/test/scala/fs2/data/mft/QuerySpec.scala
  finite-state/shared/src/test/scala/fs2/data/pfsa/RegularSpec.scala
  json/src/main/scala-2/fs2/data/json/jq/literals.scala
  json/src/main/scala-3/fs2/data/json/jq/literals.scala
  json/src/main/scala/fs2/data/json/jq/CompiledJq.scala
  json/src/main/scala/fs2/data/json/jq/Compiler.scala
  json/src/main/scala/fs2/data/json/jq/JqParser.scala
  json/src/main/scala/fs2/data/json/jq/PipedCompiledJq.scala
  json/src/main/scala/fs2/data/json/jq/TaggedMatcher.scala
  json/src/main/scala/fs2/data/json/jq/ast.scala
  json/src/main/scala/fs2/data/json/jq/internal/ESPCompiledJq.scala
  json/src/main/scala/fs2/data/json/jq/internal/ESPJqCompiler.scala
  json/src/main/scala/fs2/data/json/jq/internal/package.scala
  json/src/main/scala/fs2/data/json/jsonpath/internals/JsonQueryPipe.scala
  json/src/main/scala/fs2/data/json/jsonpath/package.scala
  json/src/main/scala/fs2/data/json/tagged/JsonTagger.scala
  json/src/main/scala/fs2/data/json/tagged/package.scala
  json/src/test/scala/fs2/data/json/jq/JqSpec.scala
  site/documentation/json/directory.conf
  site/documentation/json/index.md
  site/documentation/json/interpolators.md
  site/documentation/json/jq.md
  site/documentation/json/transformations.md
  xml/src/main/scala/fs2/data/xml/xpath/internals/LocationMatch.scala
Labels: enhancement, json

#530 Update cats-parse to 0.3.10
  build.sbt
Labels: dependency update

#529 Add cookbook for JSON data manipulation
  .github/workflows/ci.yml
  build.sbt
  examples/jqlike/src/main/scala/fs2/data/example/jqlike/JqLike.scala
  json/src/main/scala/fs2/data/json/jq/Compiler.scala
  json/src/main/scala/fs2/data/json/jq/internal/ESPJqCompiler.scala
  project/plugins.sbt
  site/cookbooks/data/json/sample.json
  site/cookbooks/jq.md
  site/directory.conf
  site/js/materialize.min.js
  site/js/stork.js
  site/js/stork.wasm
Labels: documentation, json

#525 Update play-json to 2.10.1
  .github/workflows/ci.yml
  build.sbt
Labels: dependency update

#531 Add a default fallback value to paths
  finite-state/shared/src/main/scala/fs2/data/mft/query/Query.scala
  finite-state/shared/src/main/scala/fs2/data/mft/query/QueryCompiler.scala
  finite-state/shared/src/main/scala/fs2/data/pfsa/PDFA.scala
  finite-state/shared/src/main/scala/fs2/data/pfsa/PNFA.scala
  finite-state/shared/src/main/scala/fs2/data/pfsa/Regular.scala
  finite-state/shared/src/test/scala/fs2/data/mft/QuerySpec.scala
  json/src/main/scala/fs2/data/json/jq/internal/ESPJqCompiler.scala
  json/src/test/scala/fs2/data/json/jq/JqSpec.scala
Labels: enhancement, json, finite state

#533 Fix default value
  finite-state/shared/src/main/scala/fs2/data/esp/ESP.scala
  finite-state/shared/src/main/scala/fs2/data/esp/Expr.scala
  finite-state/shared/src/main/scala/fs2/data/esp/Rhs.scala
  finite-state/shared/src/main/scala/fs2/data/mft/MFT.scala
  finite-state/shared/src/main/scala/fs2/data/mft/package.scala
  finite-state/shared/src/main/scala/fs2/data/mft/query/QueryCompiler.scala
  json/src/main/scala/fs2/data/json/jq/internal/ESPCompiledJq.scala
  json/src/main/scala/fs2/data/json/tagged/JsonTagger.scala
  json/src/test/scala/fs2/data/json/jq/JqSpec.scala
Labels: bug, json

#536 Update sbt-typelevel, sbt-typelevel-site to 0.6.0
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependency update

#537 Update play-json to 2.10.2
  build.sbt
Labels: dependency update

#538 Update sbt to 1.9.7
  project/build.properties
  scalafix/project/build.properties
Labels: dependency update

#539 Update scalafmt-core to 3.7.15
  .scalafmt.conf
Labels: dependency update

#540 Update sbt-assembly to 2.1.4
  project/plugins.sbt
Labels: dependency update
