Repository gnieh/fs2-data, pull requests merged in 2023-03, with the labels that each got.

#456 Update circe-core, circe-generic, ... to 0.14.5
  build.sbt
Labels: dependency update

#458 Update sbt-typelevel to 0.4.19
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependency update

#457 Update diffson-circe, diffson-core, ... to 4.4.0
  build.sbt
Labels: dependency update

#459 Generalize optional fields handling for `RowF`
  .github/workflows/ci.yml
  build.sbt
  csv/shared/src/main/scala/fs2/data/csv/RowF.scala
  csv/shared/src/test/scala/fs2/data/csv/RowFTest.scala
  documentation/docs/csv/index.md
  documentation/docs/json/index.md
Labels: enhancement, csv

#460 Update nscplugin, sbt-scala-native, ... to 0.4.11
  project/plugins.sbt
Labels: dependency update

#462 Fix CSV line numbers in presence of empty rows
  csv/shared/src/main/scala/fs2/data/csv/internals/RowParser.scala
  csv/shared/src/test/scala/fs2/data/csv/RowParserTest.scala
Labels: bug, csv

#463 Update nscplugin, sbt-scala-native, ... to 0.4.12
  project/plugins.sbt
Labels: dependency update
