Repository gnieh/fs2-data, pull requests merged in 2025-05, with the labels that each got.

#675 Fix XPath parsing and NFA building with alternatives
  xml/src/main/scala/fs2/data/xml/xpath/XPath.scala
  xml/src/main/scala/fs2/data/xml/xpath/XPathParser.scala
  xml/src/main/scala/fs2/data/xml/xpath/package.scala
  xml/src/test/scala/fs2/data/xml/xpath/QueryPipeSpec.scala
Labels: bug

#677 Update fs2-data-json-circe to 1.11.3
  site/cookbooks/scripts/jsonlines.scala
Labels: dependency update

#680 Update scalafmt-core to 3.9.6
  .scalafmt.conf
Labels: dependency update

#679 Make path operators more flexible
  json/circe/src/test/scala/fs2/data/json/circe/CirceJsonPathStructuredSpec.scala
  json/play/src/test/scala/fs2/data/json/playJson/PlayJsonPathStructuredSpec.scala
  json/src/main/scala/fs2/data/json/jsonpath/package.scala
  json/src/test/scala/fs2/data/json/jsonpath/JsonPathStructuredSpec.scala
  site/documentation/json/jsonpath.md
  site/documentation/xml/xpath.md
  xml/src/main/scala/fs2/data/xml/xpath/package.scala
Labels: enhancement, json, xml

#681 Update scala3-library, ... to 3.3.6
  build.sbt
Labels: dependency update
